from typing import Protocol, AsyncContextManager

from pydantic import BaseModel
from pydantic_ai.models import Model

from docassist.index.protocols import Embedder


class SamplingSlot[V: BaseModel](Protocol):
    def sample_id(self) -> int: ...
    def sample_coordinates(self) -> str: ...

    def get(self) -> V | None: ...

    def set(self, val: V | None): ...

    def clear(self): ...

    def is_empty(self) -> bool: ...

class SampleGroup[K: BaseModel, V: BaseModel](Protocol):
    def key(self) -> K: ...

    def key_type(self) -> type[K]:
        return type(self.key())

    def value_type(self) -> type[V]: ...

    def existing_samples(self) -> list[SamplingSlot[V]]: ...

    def new_sample(self, i: int | None = None) -> SamplingSlot[V]: ...
    def first_gap_sample(self) -> SamplingSlot[V]: ...

    def get_sample(self, i: int) -> SamplingSlot[V] | None:
        for x in self.existing_samples():
            if x.sample_id() == i:
                return x

    def __getitem__(self, item: int) -> SamplingSlot[V]:
        return self.get_sample(item)

class SamplingStrategy(Protocol):
    def pick_slot[K: BaseModel, V: BaseModel](self, group: SampleGroup[K, V]) -> SamplingSlot[V]: ...


class SampleGroupFactory(Protocol):
    def create[K: BaseModel, V: BaseModel](self, key: K, value_type: type[V], qualifier: str) -> SampleGroup[K, V]: ...

class SamplingController(Protocol):
    async def defer_until_success(self) -> AsyncContextManager: ...

    async def strategy(self, s: SamplingStrategy) -> AsyncContextManager: ...

class Sampler(Protocol):
    def over_model(self, model: Model) -> Model: ...
    def over_embedder(self, embedder: Embedder) -> Embedder: ...

    def controller(self) -> SamplingController: ...